{{- if not .Values.config.existingSecret }}
{{- $secretName := include "conduktor.platform.secretName" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: conduktor-platform
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  CDK_ORGANIZATION_NAME: {{ .Values.config.organization.name | default "Conduktor" | b64enc }}
  CDK_ADMIN_EMAIL: {{ required "config.admin.email and config.admin.password MUST be set in values" .Values.config.admin.email | b64enc }}
  CDK_ADMIN_PASSWORD: {{ required "config.admin.email and config.admin.password MUST be set in values" .Values.config.admin.password | b64enc }}
  CDK_DATABASE_PASSWORD: {{ required "config.database.password MUST be set in values" .Values.config.database.password | b64enc }}
  CDK_DATABASE_USERNAME: {{ required "config.database.username MUST be set in values" .Values.config.database.username | b64enc }}
{{- end }}
