{{- if not .Values.config.existingSecret }}
{{- $secretName := include "conduktor.platform.secretName" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: conduktor-platform
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $orgaName := required "config.organization.name MUST be set in values" .Values.config.organization.name  }}
  CDK_ORGANIZATION_NAME: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "CDK_ORGANIZATION_NAME" "defaultValue" $orgaName "context" $) }}
  {{- $adminEmail := required "config.admin.email and config.admin.password MUST be set in values" .Values.config.admin.email  }}
  CDK_ADMIN_EMAIL: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "CDK_ADMIN_EMAIL" "defaultValue" $adminEmail "context" $) }}
  {{ $adminPassword := required "config.admin.email and config.admin.password MUST be set in values" .Values.config.admin.password }}
  CDK_ADMIN_PASSWORD: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "CDK_ADMIN_PASSWORD" "defaultValue" $adminPassword "context" $) }}
  CDK_DATABASE_PASSWORD: {{ required "config.database.password MUST be set in values" .Values.config.database.password | b64enc }}
  CDK_DATABASE_USERNAME: {{ required "config.database.username MUST be set in values" .Values.config.database.username | b64enc }}
{{- end }}