{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" }}
{{- if and .Values.platform.metrics.enabled .Values.platform.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "conduktor.platform.serviceMonitorName" . }}
  namespace: {{ default (include "common.names.namespace" .) .Values.platform.metrics.serviceMonitor.namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: conduktor-platform
    {{- if  .Values.platform.metrics.serviceMonitor.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.platform.metrics.serviceMonitor.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.platform.metrics.serviceMonitor.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" .Values.platform.metrics.serviceMonitor.annotations .Values.commonAnnotations "context" .) | fromYaml }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.platform.metrics.serviceMonitor.jobLabel | quote }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: conduktor-platform
      {{- if .Values.platform.metrics.serviceMonitor.selector }}
      {{- include "common.tplvalues.render" (dict "value" .Values.platform.metrics.serviceMonitor.selector "context" $) | nindent 6 }}
      {{- end }}
  endpoints:
    - port: http
      path: "/api/metrics"
      scheme: http
      {{- if .Values.platform.metrics.serviceMonitor.interval }}
      interval: {{ .Values.platform.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.platform.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.platform.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.platform.metrics.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.platform.metrics.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.platform.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.platform.metrics.serviceMonitor.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.platform.metrics.serviceMonitor.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.platform.metrics.serviceMonitor.relabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.platform.metrics.serviceMonitor.extraParams }}
      {{- toYaml .Values.platform.metrics.serviceMonitor.extraParams | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ include "common.names.namespace" . | quote }}
{{- end }}
{{- end }}
