{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" }}
{{- if .Values.metrics.prometheus.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "conduktor-gateway.fullname" . | trunc 52 }}-monitoring
  labels: {{ include "conduktor-gateway.labels" . | nindent 4 }}
    {{- if .Values.metrics.prometheus.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.metrics.prometheus.labels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.metrics.prometheus.annotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.metrics.prometheus.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.metrics.prometheus.jobLabel | quote }}
  selector:
    matchLabels: {{ include "conduktor-gateway.podSelectorLabels" . | nindent 6 }}
      metrics.conduktor.io/prometheus: "true"
  endpoints:
    - port: admin-http
      path: /metrics
      {{- if .Values.metrics.prometheus.scheme }}
      scheme: {{ .Values.metrics.prometheus.scheme | quote }}
      {{- else }}
      scheme: {{ include "conduktor-gateway.adminAPIScheme" . | quote }}
      {{- end }}
      {{- if .Values.metrics.prometheus.metricRelabelings }}
      metricRelabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.metrics.prometheus.metricRelabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.prometheus.relabelings }}
      relabelings: {{- include "common.tplvalues.render" ( dict "value" .Values.metrics.prometheus.relabelings "context" $) | nindent 8 }}
      {{- end }}
      {{- if and .Values.gateway.admin.securedMetrics (not .Values.gateway.secretRef) }}
      basicAuth:
        username:
          name: {{ include "conduktor-gateway.secretName" . }}
          key: {{ .Values.gateway.admin.mainAdminSecretKeys.username | quote}}
        password:
          name: {{ include "conduktor-gateway.secretName" . }}
          key: {{ .Values.gateway.admin.mainAdminSecretKeys.password | quote}}
      {{- end }}
      {{- if .Values.metrics.prometheus.tlsConfig }}
      tlsConfig: {{- include "common.tplvalues.render" ( dict "value" .Values.metrics.prometheus.tlsConfig "context" $) | nindent 8 }}
      {{- else }}
      {{- if eq ( include "conduktor-gateway.adminAPIScheme" .) "https" }}
      tlsConfig:
        {{/* Skip TLS validation because we can't extract the CA/Cert from a JKS keystore inside helm to configure Prometheus*/}}
        insecureSkipVerify: true
      {{- end }}
      {{- end }}
      {{- if .Values.metrics.prometheus.extraParams }}
      {{- toYaml .Values.metrics.prometheus.extraParams | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
