{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/PrometheusRule" }}
{{- if .Values.metrics.alerts.enable  }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "conduktor-gateway.fullname" . | trunc 51 }}-gateway-alert
  namespace: {{ .Release.Namespace }}
  labels: {{ include "conduktor-gateway.labels" . | nindent 4 }}
    release: prometheus
spec: {{ $.Files.Get "prometheus-alerts/gateway-alerts.yaml" | nindent 2}}
{{- end }}
{{- end }}
