{{- if and (eq (include "conduktor-gateway.useLegacyPortRange" .) "false") (eq .Values.gateway.listeners.internal.routing "sni") }}
{{- $brokerData := include "conduktor-gateway.expandBrokerIds" .Values.gateway.kafka.brokerIds | fromJson }}
{{- $portData := include "conduktor-gateway.portPairsJson" .Values.gateway.listeners.internal.ports | fromJson }}
{{- range $brokerData.ids }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "conduktor-gateway.brokerSniServiceName" (dict "id" . "context" $) }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{ include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: conduktor-gateway
spec:
  type: ClusterIP
  ports:
    {{- range $portData.pairs }}
    - name: broker-{{ .advertised }}
      port: {{ .advertised }}
      targetPort: {{ .local }}
      protocol: TCP
    {{- end }}
  selector: {{ include "conduktor-gateway.podSelectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
