{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "conduktor-gateway.serviceAccountName" . }}
  labels: {{ include "conduktor-gateway.labels" . | nindent 4 }}
{{- end -}}
