apiVersion: v1
kind: Service
metadata:
  name:  {{ include "conduktor-gateway.internalServiceName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: conduktor-gateway
    {{- with .Values.service.internal.labels }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.metrics.prometheus.enable }}
    metrics.conduktor.io/prometheus: {{ .Values.metrics.prometheus.enable | quote }}
    {{- end }}
  {{- if or .Values.service.internal.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.service.internal.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    {{- range untilStep (int .Values.gateway.portRange.start) (int (add .Values.gateway.portRange.start .Values.gateway.portRange.count)) 1 }}
    - name: broker-gateway-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
    {{- end }}
    - name: admin-http
      port: {{ .Values.gateway.admin.port }}
      targetPort: {{ .Values.gateway.admin.port }}
      protocol: TCP
    {{- if .Values.gateway.jmx.enable }}
    - name: jmx
      port: {{ .Values.gateway.jmx.port }}
      targetPort: {{ .Values.gateway.jmx.port }}
      protocol: TCP
    {{- end }}
  selector: {{ include "conduktor-gateway.podSelectorLabels" . | nindent 4 }}
