{{- if .Values.service.external.enable }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "conduktor-gateway.externalServiceName" . }}
  labels: {{ include "conduktor-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.external.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.external.type }}
  {{- if .Values.service.external.ip }}
  loadBalancerIP: {{ .Values.service.external.ip }}
  {{- end }}
  ports:
    {{- range untilStep (int .Values.gateway.portRange.start) (int (add .Values.gateway.portRange.start .Values.gateway.portRange.count)) 1 }}
    - name: broker-gateway-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.external.admin }}
    - name: admin-http
      port: {{ .Values.gateway.admin.port }}
      targetPort: {{ .Values.gateway.admin.port }}
      protocol: TCP
    {{- end }}
    {{- if and .Values.gateway.jmx.enable .Values.service.external.jmx }}
    - name: jmx
      port: {{ .Values.gateway.jmx.port }}
      targetPort: {{ .Values.gateway.jmx.port }}
      protocol: TCP
    {{- end }}
  selector: {{ include "conduktor-gateway.podSelectorLabels" . | nindent 4 }}
{{- end }}
