{{- if .Values.service.external.enable }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "conduktor-gateway.externalServiceName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{ include "conduktor-gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: conduktor-gateway
    {{- with .Values.service.external.labels }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.service.external.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.service.external.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.external.type }}
  {{- if .Values.service.external.ip }}
  loadBalancerIP: {{ .Values.service.external.ip }}
  {{- end }}
  {{- if .Values.service.external.extraSpecs }}
  {{- include "common.tplvalues.render" (dict "value" .Values.service.external.extraSpecs "context" $) | nindent 2 }}
  {{- end }}
  ports:
    {{- range untilStep (int .Values.gateway.portRange.start) (int (add .Values.gateway.portRange.start .Values.gateway.portRange.count)) 1 }}
    - name: broker-gateway-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.external.admin }}
    - name: admin-http
      port: {{ .Values.gateway.admin.port }}
      targetPort: {{ .Values.gateway.admin.port }}
      protocol: TCP
    {{- end }}
    {{- if and .Values.gateway.jmx.enable .Values.service.external.jmx }}
    - name: jmx
      port: {{ .Values.gateway.jmx.port }}
      targetPort: {{ .Values.gateway.jmx.port }}
      protocol: TCP
    {{- end }}
  selector: {{ include "conduktor-gateway.podSelectorLabels" . | nindent 4 }}
{{- end }}
