#!/usr/bin/env bash

set -eu

echo "Lint charts"
helm lint charts/gateway

# set mandatory values
helm lint charts/console --set config.organization.name=test,config.admin.email=test@test.io,config.admin.password=test,config.database.password=test,config.database.username=test,config.database.host=test

echo "Update charts README"
make generate-readme
