{
 "title": "Conduktor Gateway logs",
 "tags": [
  "Conduktor",
  "conduktor-gateway",
  "Logs",
  "Pod"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "${INPUT_DS_PROMETHEUS}" },
   { "name": "loki_datasource", "query": "${INPUT_DS_LOKI}" },
   { "name": "job", "label": "job", "query": "${INPUT_GATEWAY_JOB_NAME}" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(up{job=\"$job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Log count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (count_over_time({pod=~\"${pod}\"} | pod =~ `$pod` [$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Warn|Error log count [1m] for $pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "repeat": "pod",
   "targets": [
    {
     "expr": "sum by(pod, level) (count_over_time({pod=~\"${pod}\"} | pod =~ `$pod` | json level=\"level\" | __error__=`` | level =~ `ERROR|WARN` [$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{pod=~\"${pod}\"} | pod =~ `$pod` | json level=\"level\", message=\"message\", thread=\"thread\", logger=\"loggerName\", pod=\"pod\" | __error__=`` | line_format `{{.message}}`",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}