{
 "title": "Conduktor Gateway",
 "description": "Dashboard for Conduktor Gateway",
 "tags": [
  "Conduktor",
  "conduktor-gateway",
  "JVM",
  "Pod"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "${INPUT_DS_PROMETHEUS}" },
   { "name": "job", "label": "job", "query": "${INPUT_GATEWAY_JOB_NAME}" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{job=\"$job\"}, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", area=\"nonheap\"},id)"
    }
   },
   { "name": "vcluster", "label": "vCluster", "query": { "query": "label_values(vcluster)" } },
   {
    "name": "jvm_threads_states_threads",
    "label": "JVM Thread State",
    "query": {
     "query": "label_values(jvm_threads_states_threads{job=\"$job\",  pod=~\"$pod\"},state)"
    }
   },
   {
    "name": "gateway_kcache_size_type",
    "label": "kcache_key",
    "query": {
     "query": "label_values(gateway_kcache_size{job=\"$job\", pod=~\"$pod\"},type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "License expiration in days",
   "type": "gauge",
   "description": "Number of remaining days until license expiration.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(min(gateway_license_remaining_days{job=\"$job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License expiration date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(abs(min(gateway_license_remaining_days{job=\"$job\"})) * 86400 + time()) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Number of Gateway/Kafka nodes and vclusters (include undefined one)",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(pod) (gateway_thread_request_rebuild_total{job=\"$job\", pod=~\"$pod\"}))",
     "legendFormat": "Gateway Nodes"
    },
    {
     "expr": "avg(gateway_upstream_io_nodes{job=\"$job\"})",
     "legendFormat": "Kafka Nodes"
    },
    {
     "expr": "count(sum by(vcluster) (gateway_thread_request_rebuild_total{job=\"$job\", pod=~\"$pod\"}))",
     "legendFormat": "vClusters"
    }
   ]
  },
  {
   "title": "Global rates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(gateway_thread_request_rebuild_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Requests/s"
    },
    {
     "expr": "sum(rate(gateway_bytes_exchanged_vcluster_total{job=\"$job\", direction=\"upstream\"}[$__rate_interval]))",
     "legendFormat": "Upstream bytes/s"
    },
    {
     "expr": "sum(rate(gateway_bytes_exchanged_vcluster_total{job=\"$job\", direction=\"downstream\"}[$__rate_interval]))",
     "legendFormat": "Downstream bytes/s"
    },
    {
     "expr": "sum(irate(gateway_apiKeys_throttle_ms_seconds_sum{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Throttle ms"
    }
   ]
  },
  { "title": "Kafka gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Sum of requests per second from all selected pods.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(gateway_thread_request_rebuild_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests Latency",
   "type": "timeseries",
   "description": "Average/p90/p99 requests/responses time latency for all pods",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gateway_latency_request_response_seconds_sum{job=\"$job\",pod=~\"$pod\"}[$__rate_interval])) / sum(rate(gateway_latency_request_response_seconds_count{job=\"$job\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Average Latency"
    },
    {
     "expr": "max(histogram_quantile(0.9, rate(gateway_latency_request_response_seconds_bucket{job=\"$job\",pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P90 Latency"
    },
    {
     "expr": "max(histogram_quantile(0.99, rate(gateway_latency_request_response_seconds_bucket{job=\"$job\",pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P99 Latency"
    }
   ]
  },
  {
   "title": "Total throttling rate",
   "type": "timeseries",
   "description": "Sum of kafka throttling rates for all selected pods for all ApiKeys",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(irate(gateway_apiKeys_throttle_ms_seconds_sum{job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total throttling"
    }
   ]
  },
  {
   "title": "Total Exchanged Bytes increase ",
   "type": "timeseries",
   "description": "Increase of exchanged bytes \nDownstream is between clients & Gateway,\nUpstream is between Gateway & Kafka",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(direction) (rate(gateway_bytes_exchanged_vcluster_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Number of connections to Kafka created and closed (/s)",
   "type": "timeseries",
   "description": "Sum of opened/closed connection to Kafka cluster from all selected pods",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum by(job) (increase(gateway_upstream_connection_close_rate_seconds_count{job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Connection closed"
    },
    {
     "expr": "sum by(job) (increase(gateway_upstream_connection_creation_rate_seconds_count{job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Connection created"
    }
   ]
  },
  {
   "title": "P99 Latency per Pod",
   "type": "timeseries",
   "description": "P99 request-response latency per Gateway pod. Identifies uneven load distribution.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(gateway_latency_request_response_seconds_bucket{job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Per ApiKey ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Requests/s / API key",
   "type": "timeseries",
   "description": "Sum of received requests per Kafka APIKey from all selected pods and vClusters.\nFilter FETCH and PRODUCE apiKey by default.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(api_key) (rate(gateway_thread_request_rebuild_total{vcluster=~\"$vcluster\", job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{api_key}}"
    }
   ]
  },
  {
   "title": "Throttling / API key",
   "type": "timeseries",
   "description": "Kafka throttling rates per ApiKey from all selected pods and vCluisters  ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(apiKeys) (irate(gateway_apiKeys_throttle_ms_seconds_sum{vcluster=~\"$vcluster\", job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{apiKeys}}"
    }
   ]
  },
  {
   "title": "Avg Latency / API key",
   "type": "timeseries",
   "description": "Average latency per Kafka API key. Identifies which operations contribute most to overall latency.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(apiKeys) (rate(gateway_apiKeys_latency_request_response_seconds_sum{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])) / sum by(apiKeys) (rate(gateway_apiKeys_latency_request_response_seconds_count{job=\"$job\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{apiKeys}}"
    }
   ]
  },
  {
   "title": "Max Latency / API key",
   "type": "timeseries",
   "description": "Maximum latency per Kafka API key. Shows worst-case latency, identifies P99 contributors.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(apiKeys) (gateway_apiKeys_latency_request_response_seconds_max{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "{{apiKeys}}"
    }
   ]
  },
  {
   "title": "Upstream IO Wait (Backend Kafka Latency Proxy)",
   "type": "timeseries",
   "description": "Max I/O wait time per pod. High values indicate backend Kafka is slow to respond.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(pod) (gateway_upstream_io_wait_rate_seconds_max{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pending Thread Tasks",
   "type": "timeseries",
   "description": "Pending tasks on Gateway threads. High values indicate Gateway is backed up.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (gateway_thread_tasks{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Per vCluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Requests / vcluster",
   "type": "timeseries",
   "description": "Sum of requests per second per vCluster from all selected pods",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(vcluster) (rate(gateway_thread_request_rebuild_total{job=\"$job\", pod=~\"$pod\", vcluster=~\"$vcluster\"}[$__rate_interval])) > 0",
     "legendFormat": "{{vcluster}}"
    }
   ]
  },
  {
   "title": "Total Exchanged Bytes increase per Vcluster",
   "type": "timeseries",
   "description": "Increase of exchanged bytes per vcluster\nDownstream is between clients & Gateway,\nUpstream is between Gateway & Kafka",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(direction, vcluster) (increase(gateway_bytes_exchanged_vcluster_total{job=\"$job\", pod=~\"$pod\", vcluster=~\"$vcluster\"}[$__rate_interval]))",
     "legendFormat": "{{vcluster}} - {{direction}}"
    }
   ]
  },
  { "title": "Per Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Total Exchanged Bytes increase per Topic",
   "type": "timeseries",
   "description": "Rate of exchanged bytes per topic\nDownstream is between clients & Gateway,\nUpstream is between Gateway & Kafka",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic, direction) (increase(gateway_bytes_exchanged_topic_total{job=\"$job\", pod=~\"$pod\", vcluster=~\"$vcluster\"}[$__rate_interval]))",
     "legendFormat": "Topic {{topic}} on {{direction}} "
    }
   ]
  },
  { "title": "Per username", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Requests /  user & vcluster",
   "type": "timeseries",
   "description": "Sum of requests per second per user on vCluster from all selected pods/vclusters",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(vcluster, username) (rate(gateway_current_inflight_apiKeys_total{job=\"$job\", pod=~\"$pod\", vcluster=~\"$vcluster\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{username}} on {{vcluster}}"
    }
   ]
  },
  { "title": "Pod resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Stacked CPU Usage per pod",
   "type": "timeseries",
   "description": "Show each pod CPU usage with total of resource CPU requests and limits for the selected pods.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{pod=~\"$pod\"})",
     "legendFormat": "total - requests"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{pod=~\"$pod\"})",
     "legendFormat": "total - limits"
    }
   ]
  },
  {
   "title": "Stacked Memory Usage per pod",
   "type": "timeseries",
   "description": "Show each pod memory usage with total of resource memory requests and limits for the selected pods.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{ pod=~\"$pod\"})",
     "legendFormat": "total - requests"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{pod=~\"$pod\"})",
     "legendFormat": "total - limits"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", area=\"heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\", area=\"heap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 102 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 102 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "max"
      },
      {
       "expr": "process_memory_rss_bytes{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "rss"
      },
      {
       "expr": "process_memory_pss_bytes{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "pss"
      },
      {
       "expr": "process_memory_swap_bytes{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "swap"
      },
      {
       "expr": "process_memory_swappss_bytes{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "swappss"
      },
      {
       "expr": "process_memory_pss_bytes{job=\"$job\", pod=~\"$pod\"} + process_memory_swap_bytes{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "phys (pss+swap)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "system_cpu_usage{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "system - {{ pod }}"
      },
      {
       "expr": "process_cpu_usage{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "process - {{ pod }}"
      },
      {
       "expr": "avg_over_time(process_cpu_usage{job=\"$job\", pod=~\"$pod\"}[1h])",
       "legendFormat": "process-1h - {{ pod }}"
      }
     ]
    },
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(system_load_average_1m{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "system-1m"
      },
      {
       "expr": "sum(system_cpu_count{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_live_threads{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "live"
      },
      {
       "expr": "sum(jvm_threads_daemon_threads{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "daemon"
      },
      {
       "expr": "sum(jvm_threads_peak_threads{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "peak"
      },
      {
       "expr": "sum(process_threads{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(process_files_open_files{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "open"
      },
      {
       "expr": "sum(process_files_max_files{job=\"$job\", pod=~\"$pod\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_heap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_heap\"})",
       "legendFormat": "commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_heap\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_nonheap\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_duration_seconds_count{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{action}} ({{cause}}) - {{ pod }}"
      },
      {
       "expr": "rate(jvm_gc_pause_seconds_count{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{action}} ({{cause}})  - {{ pod }}"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_duration_seconds_sum{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])/increase(jvm_gc_pause_duration_seconds_count{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "avg {{action}} ({{cause}}) - {{ pod }}"
      },
      {
       "expr": "jvm_gc_pause_duration_seconds_max{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "max {{action}} ({{cause}}) - {{ pod }}"
      },
      {
       "expr": "increase(jvm_gc_pause_seconds_sum{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])/increase(jvm_gc_pause_seconds_count{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "avg {{action}} ({{cause}}) - {{ pod }}"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "max {{action}} ({{cause}}) - {{ pod }}"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded_classes{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class load/unload rate (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded_classes{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "class load rate"
      },
      {
       "expr": "delta(jvm_classes_unloaded_total{job=\"$job\", pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "class unload rate"
      },
      {
       "expr": "jvm_classes_loaded_total{job=\"$job\", pod=~\"$pod\"}-jvm_classes_unloaded_total{job=\"$job\", pod=~\"$pod\"}",
       "legendFormat": "class unload rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{job=\"$job\", pod=~\"$pod\", id=\"direct\"}",
       "legendFormat": "used - {{ pod }}"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{job=\"$job\", pod=~\"$pod\", id=\"direct\"}",
       "legendFormat": "capacity - {{ pod }}"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{job=\"$job\", pod=~\"$pod\", id=\"direct\"}",
       "legendFormat": "count - {{ pod }}"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{job=\"$job\", pod=~\"$pod\", id=\"mapped\"}",
       "legendFormat": "used - {{ pod }}"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{job=\"$job\", pod=~\"$pod\", id=\"mapped\"}",
       "legendFormat": "capacity - {{ pod }}"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count_buffers{job=\"$job\", pod=~\"$pod\", id=\"mapped\"}",
       "legendFormat": "count - {{ pod }}"
      }
     ]
    }
   ]
  }
 ]
}