# Test is checking:
# - generate a self-signed certificate for the platform
# - connectivity between the platform and the monitoring pod using self-signed certificate
# - use hosts list for database configuration
nameOverride: cdkt-test-02
config:
  organization:
    name: conduktor
  admin:
    email: admin@conduktor.io
    password: testP4ss!

  database:
    name: platform
    hosts:
      - host: postgresql-hl
        port: 5432
    password: conduktor123
    username: postgres

  platform:
    external:
      url: "https://platform.cluster.local"
    https:
      selfSigned: true

platform:
  startupProbe:
    initialDelaySeconds: 60  # extra delay because of limited cpu resources
  terminationGracePeriodSeconds: 0  # quick kill between tests
  resources:
    limits:
      cpu: 1500m
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi

platformCortex:
  resources:
    limits:
      cpu: 500m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 200Mi

tests:
  enabled: true
