# Test is checking:
# - use existing secret for platform tls
# - connectivity between the platform and the monitoring pod skipping tls verification
nameOverride: cdkt-test-03
config:
  organization:
    name: conduktor
  admin:
    email: admin@conduktor.io
    password: admin

  database:
    name: platform
    host: postgresql-hl
    password: conduktor123
    port: 5432
    username: postgres

  platform:
    external:
      url: "https://platform.cluster.local"
    https:
      selfSigned: false
      existingSecret: "cdkt-test-03-tls"

monitoringConfig:
  scraper:
    skipSSLCheck: true

ingress:
  secrets:
    - name: cdkt-test-03-tls
      certificate: |-
        -----BEGIN CERTIFICATE-----
        MIIDNjCCAh6gAwIBAgIUP7t+XFOtCuqOuBe0YWj/XrUSNS0wDQYJKoZIhvcNAQEL
        BQAwITEfMB0GA1UEAwwWcGxhdGZvcm0uY2x1c3Rlci5sb2NhbDAeFw0yMzA4MTEx
        NDEzMDJaFw0yMzA5MTAxNDEzMDJaMCExHzAdBgNVBAMMFnBsYXRmb3JtLmNsdXN0
        ZXIubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCmfcTsrw0b
        hGeHm1ODH4ULOO5smnHLN6VRkv4asswSKrU+9yyknINfzZ42LPA2zVkhWnr3qAUl
        xl5zXUSxyYme+xXEta3SowK1BUBiJvkwry39B3q05+lR/aCYEyo/aKXQ1smFrs0t
        JX2dFNby4Lxn8RYjXgVnz2aFxkEAn0sTTY9wCFrCbyvAJAQSWnKiWDulGv0l3z5q
        rXbWuqbKfNclk/EkMo9/JB8fAEKxDHpcer7sm4L5q8zFrZeubhNRKsd39vc4nwqh
        I5dLuuetI5WkEv2d74AQJHhrTLMsO2GcQN1LQl5a/mP6K4oJ3XhIH8Uw1+KW9soU
        NqjWY7RNDm1xAgMBAAGjZjBkMCEGA1UdEQQaMBiCFnBsYXRmb3JtLmNsdXN0ZXIu
        bG9jYWwwCwYDVR0PBAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQW
        BBRwPeqPdyGShBKjUdVIO84EvDixujANBgkqhkiG9w0BAQsFAAOCAQEAQxdeGfEl
        XD5ZpiZg5zVvULJEZaT6HcdJ3iTgIKRmuJK6xi6eM4fWHHlJA11S/d+CEqzjqTwV
        PHQf3ZAxhWAhM8Kdwnhk+8j5eMzCUj4OiXbqLamhKAUkfNckOSP0DxHOPG26qLmX
        Av2TtG2z/XQe70aMBhXhPlbk60Dr0py6anR/51ppBf+d/O4wxIZYWtS72dYzLUFI
        icqrHKwIBmBy54MJijUmM5QC7qUSemncjZco5XDPaquirQI1i0yRebla3WqfO4II
        S/Ukxk0mgZeQ+pVnNgrPRNktcsaFw/TRoqhh7BU67DSSipdeXXVCiRG9eVTxEpY3
        aCVYlF1cM8BoHw==
        -----END CERTIFICATE-----
      key: |-
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmfcTsrw0bhGeH
        m1ODH4ULOO5smnHLN6VRkv4asswSKrU+9yyknINfzZ42LPA2zVkhWnr3qAUlxl5z
        XUSxyYme+xXEta3SowK1BUBiJvkwry39B3q05+lR/aCYEyo/aKXQ1smFrs0tJX2d
        FNby4Lxn8RYjXgVnz2aFxkEAn0sTTY9wCFrCbyvAJAQSWnKiWDulGv0l3z5qrXbW
        uqbKfNclk/EkMo9/JB8fAEKxDHpcer7sm4L5q8zFrZeubhNRKsd39vc4nwqhI5dL
        uuetI5WkEv2d74AQJHhrTLMsO2GcQN1LQl5a/mP6K4oJ3XhIH8Uw1+KW9soUNqjW
        Y7RNDm1xAgMBAAECggEAARNQ7esEAewVit53wCVLlvoOR+rWVOoPBHwqh0+/IjFb
        tO+0VOHuFl5Z6qoyReLzg9Pgu9f7KtTJfdPOnpPuPBXnP86HlDO7CY78A18Y883K
        4lG6b7/lTbMec6MHWwwTd6CRwhryC3jMtmkI1sSfvokws8GbvEFrRvsqWfOddzJb
        Z3nGRW6qclYOSjyrsNUJYfmDiir59EQZd0MojwMXdJR9seX/3ORs5f38vYIIhaIv
        IrnOKGdVdvpP7EhTD5Ul/0Y/chrxvW5UrKtynC3FT4GSjDtLLEFJudC9hpnIHiEj
        mZas8JJfucZ3AYpFPgmLSZuX2MFhZZTKrJ/j6vw7QQKBgQDYYaF6Ev8WTqE1tT1q
        n6yLQbfc34O4SpVAd0qTOva3fuRQZ2RuuTgA6IaElTqFkk+H86agk/yqLJDqKbjm
        +tbfsMdhTQMGtCjbydg6CW5Fs1+r/n7Pkg+eoWUTIFqTJ1totnu7RtQtR2osmWmK
        X1hk7C63CxDXsB6nNKqRLQz0QQKBgQDE+ahkqyb0sGxByUDYFbPliUCSpU2+5d2U
        rdcIO4F07Q4GQtJejNQzEKLrYd6+NhWs11rVrXYwlS4fm/nOIBgQy154KKWM04QL
        q4mCeCCQxcDHbVRPb51TF9nMLl9wQeY7NuaQbMFlErb5pIDKS1Nt0BFSlPmquYwl
        kokx9JRtMQKBgGxhano0raREuiamox6W39vYjPmK0vUqFlv15FqefBko678CKqHz
        EAQUc9xQysFAqalU9y8TMMkkDWncgArhtWLRruwjoNJoxtZf4XggZSVwVQlXLblW
        VZCFEpVj7TorynNGg+8n6PrM/HdeWCjA3Quf6T4xwrvmMVRa4txYjlaBAoGAFQC5
        3+IQCU82e91FuMS3peX4qKpPm+dOtSfEIfCWYS1VrX06iTJi/f7sIEUTRxzlOsTL
        vrT8QTnm7R/ohv4NEt1ceVt8K4PyNHxZ8Tt13Xn4kEssDjxMfiuw4YCgVIvyTKYR
        95xhErHoKL5NrURS5QamkjOoW3flZaw2TMlTekECgYEAnRMZQTESwA5Mp311Cggx
        CuYIXw/G4Dk/pD7VTvdTTaJY+ShUXLcOCeri1UysQc2L1C6owgvzhr6oMymJirYX
        wvgKzW/jdP22DuI9njmCzeX6Qy+Ip6tBUe5A+fi5uQ1sqZj3jPB/9GOf/etw+Jes
        Q33adkf6WrEn/aN9RAFyiAY=
        -----END PRIVATE KEY-----

platform:
  startupProbe:
    initialDelaySeconds: 60  # extra delay because of limited cpu resources
  terminationGracePeriodSeconds: 0  # quick kill between tests
  resources:
    limits:
      cpu: 1500m
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi

platformCortex:
  resources:
    limits:
      cpu: 500m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 200Mi

tests:
  enabled: true
