# Test is checking:
# - basic usage of the chart is working with external monitoring storage
# - Set use secret for database configuration
nameOverride: cdkt-test-05
config:
  existingSecret: cdkt-test-05-console-config
  organization:
    name: conduktor
  admin:
    email: admin@conduktor.io
    password: testP4ss!

monitoringConfig:
  existingSecret: cdkt-test-05
  storage:
    s3:
      endpoint: "minio:9000"
      bucket: "conduktor"
      insecure: true

platform:
  startupProbe:
    initialDelaySeconds: 60  # extra delay because of limited cpu resources
  terminationGracePeriodSeconds: 0  # quick kill between tests
  resources:
    limits:
      cpu: 1500m
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 2Gi

platformCortex:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 200Mi

extraDeploy:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: cdkt-test-05
      namespace: ct
      annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "-99"
        "helm.sh/hook-delete-policy": before-hook-creation
    type: Opaque
    stringData:
      CDK_MONITORING_STORAGE_S3_ACCESSKEYID: "admin"
      CDK_MONITORING_STORAGE_S3_SECRETACCESSKEY: "conduktor123"
  - apiVersion: v1
    kind: Secret
    metadata:
      name: cdkt-test-05-console-config
      namespace: ct
      annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "-99"
        "helm.sh/hook-delete-policy": before-hook-creation
    type: Opaque
    stringData:
      CDK_DATABASE_HOSTS_0_HOST: "postgresql-hl"
      CDK_DATABASE_HOSTS_0_PORT: "5432"
      CDK_DATABASE_NAME: "platform"
      CDK_DATABASE_USERNAME: "postgres"
      CDK_DATABASE_PASSWORD: "conduktor123"

tests:
  enabled: true
  minio: true