{{- if and .Values.platformCortex.enabled (not .Values.monitoringConfig.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "conduktor.platformCortex.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: conduktor-platform-cortex
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- /* S3 configuration */ -}}
  {{- if .Values.monitoringConfig.storage.s3 }}
  {{- with .Values.monitoringConfig.storage.s3 }}
  {{ include "conduktor.monitoring.envSecret" (dict "name" "CDK_MONITORING_STORAGE_S3_ACCESSKEYID" "value" .accessKeyId) }}
  {{ include "conduktor.monitoring.envSecret" (dict "name" "CDK_MONITORING_STORAGE_S3_SECRETACCESSKEY" "value" .secretAccessKey) }}
  {{- end }}
  {{- end }}

  {{- /* GCS configuration */ -}}
  {{- if .Values.monitoringConfig.storage.gcs }}
  {{- with .Values.monitoringConfig.storage.gcs }}
  {{ include "conduktor.monitoring.envSecret" (dict "name" "CDK_MONITORING_STORAGE_GCS_SERVICEACCOUNT" "value" .serviceAccount ) }}
  {{- end }}
  {{- end }}

  {{- /* AZURE configuration */ -}}
  {{- if .Values.monitoringConfig.storage.azure }}
  {{- with .Values.monitoringConfig.storage.azure }}
  {{ include "conduktor.monitoring.envSecret" (dict "name" "CDK_MONITORING_STORAGE_AZURE_ACCOUNTNAME" "value" .accountName ) }}
  {{ include "conduktor.monitoring.envSecret" (dict "name" "CDK_MONITORING_STORAGE_AZURE_ACCOUNTKEY" "value" .accountKey ) }}
  {{- end }}
  {{- end }}

  {{- /* SWIFT configuration */ -}}
  {{- if .Values.monitoringConfig.storage.swift }}
  {{- with .Values.monitoringConfig.storage.swift }}
  {{ include "conduktor.monitoring.envSecret" (dict "name" "CDK_MONITORING_STORAGE_SWIFT_PASSWORD" "value" .password ) }}
  {{ include "conduktor.monitoring.envSecret" (dict "name" "CDK_MONITORING_STORAGE_SWIFT_USERID" "value" .userId ) }}
  {{ include "conduktor.monitoring.envSecret" (dict "name" "CDK_MONITORING_STORAGE_SWIFT_USERNAME" "value" .username ) }}
  {{- end }}
  {{- end }}
{{- end }}
