{{- if not .Values.platformCortex.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "conduktor.platformCortex.secretName" . }}
  namespace: {{ include "common.names.namespace" . | b64enc }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: conduktor-platform-cortex
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.monitoringConfig.storage.s3 }}
  CDK_MONITORING_STORAGE_S3_ACCESSKEYID: {{ .Values.monitoringConfig.storage.s3.accessKeyId | b64enc }}
  CDK_MONITORING_STORAGE_S3_SECRETACCESSKEY: {{ .Values.monitoringConfig.storage.s3.secretAccessKey | b64enc }}
  {{- end }}

  {{- if .Values.monitoringConfig.storage.gcs }}
  CDK_MONITORING_STORAGE_GCS_SERVICEACCOUNT: {{ .Values.monitoringConfig.storage.gcs.serviceAccount | b64enc }}
  {{- end }}

  {{- if .Values.monitoringConfig.storage.azure }}
  CDK_MONITORING_STORAGE_AZURE_ACCOUNTNAME: {{ .Values.monitoringConfig.storage.azure.accountName | b64enc }}
  CDK_MONITORING_STORAGE_AZURE_ACCOUNTKEY: {{ .Values.monitoringConfig.storage.azure.accountKey | b64enc }}
  {{- end }}

  {{- if .Values.monitoringConfig.storage.swift }}
  CDK_MONITORING_STORAGE_SWIFT_PASSWORD: {{ .Values.monitoringConfig.storage.swift.password | b64enc }}
  CDK_MONITORING_STORAGE_SWIFT_USERID: {{ .Values.monitoringConfig.storage.swift.userId | b64enc }}
  CDK_MONITORING_STORAGE_SWIFT_USERNAME: {{ .Values.monitoringConfig.storage.swift.username | b64enc }}
  {{- end }}
{{- end }}
