apiVersion: v2
appVersion: 1.17.2
version: 1.0.0
description: Helm chart to deploy Conduktor Platform on Kubernetes
icon: https://www.conduktor.io/svgs/logo/symbol.svg
home: https://www.conduktor.io
maintainers:
  - name: Conduktor Platform
    email: support@conduktor.io
    url: https://docs.conduktor.io/platform
name: platform
sources:
  - https://github.com/conduktor/conduktor-public-charts/tree/main/charts/platform
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
