{
 "title": "Conduktor Proxy",
 "description": "Dashboard for Kafka Proxy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "conduktor-proxy" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(up{job=\"$job\"}, pod)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(proxy_latency_request_response_seconds{job=\"$job\", pod=~\"$pod\"},tenant)"
    }
   },
   {
    "name": "jvm_threads_states_threads",
    "label": "JVM Thread State",
    "query": {
     "query": "label_values(jvm_threads_states_threads{job=\"$job\",  pod=~\"$pod\"},state)"
    }
   },
   {
    "name": "proxy_kcache_size_type",
    "label": "kcache_key",
    "query": {
     "query": "label_values(proxy_kcache_size{job=\"$job\", pod=~\"$pod\"},type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$proxy_kcache_size_type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "repeat": "proxy_kcache_size_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "proxy_kcache_size{job=\"$job\", pod=~\"$pod\", type=\"$proxy_kcache_size_type\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Global latency request response",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(proxy_latency_request_response_seconds_sum{job=\"$job\", pod=~\"$pod\", tenant=~\"$tenant\"}[$__range])) / sum(irate(proxy_latency_request_response_seconds_count{job=\"$job\", pod=~\"$pod\", tenant=~\"$tenant\"}[$__range])) > 0",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.3, sum(rate(proxy_latency_request_response_seconds_bucket{job=\"$job\", pod=~\"$pod\", tenant=~\"$tenant\"}[$__range])) by (le)) > 0",
     "legendFormat": "[30p]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(proxy_latency_request_response_seconds_bucket{job=\"$job\", pod=~\"$pod\", tenant=~\"$tenant\"}[$__range])) by (le)) > 0",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(proxy_latency_request_response_seconds_bucket{job=\"$job\", pod=~\"$pod\", tenant=~\"$tenant\"}[$__range])) by (le)) > 0",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(proxy_latency_request_response_seconds_bucket{job=\"$job\", pod=~\"$pod\", tenant=~\"$tenant\"}[$__range])) by (le)) > 0",
     "legendFormat": "[99p]"
    }
   ]
  },
  {
   "title": "Bytes  Exchanged Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(direction) (increase(proxy_bytes_exchanged_total{job=\"$job\", pod=~\"$pod\"}[$__range]))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Active Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "proxy_brokered_active_connections{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "proxy_brokered - {{ pod }}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(proxy_thread_request_received_total{job=\"$job\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(proxy_thread_request_rebuild_total{job=\"$job\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "Rebuild"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (proxy_thread_tasks{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(name) (proxy_thread_tasks{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebuild rate / tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(tenant) (rate(proxy_thread_request_rebuild_total{job=\"$job\", pod=~\"$pod\"}[1m])) > 0",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Api keys",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (api_key) (increase(proxy_thread_request_rebuild_total{tenant=~\"$tenant\", job=\"$job\", pod=~\"$pod\"}[$__range])) > 0)",
     "legendFormat": "{{api_key}}"
    }
   ]
  },
  {
   "title": "Tenant latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency request response by tenant  $tenant",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
     "repeat": "tenant",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(proxy_latency_request_response_seconds_sum{job=\"$job\", pod=~\"$pod\", tenant=\"$tenant\"} [1m])) / sum(irate(proxy_latency_request_response_seconds_count{job=\"$job\", pod=~\"$pod\", tenant=\"$tenant\"}[1m]))",
       "legendFormat": "[avg]"
      },
      {
       "expr": "histogram_quantile(0.3, sum(rate(proxy_latency_request_response_seconds_bucket{ job=\"$job\", pod=~\"$pod\", tenant=\"$tenant\"}[1m])) by (le))",
       "legendFormat": "[30p]"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(proxy_latency_request_response_seconds_bucket{ job=\"$job\", pod=~\"$pod\", tenant=\"$tenant\"}[1m])) by (le))",
       "legendFormat": "[med]"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(proxy_latency_request_response_seconds_bucket{ job=\"$job\", pod=~\"$pod\", tenant=\"$tenant\"}[1m])) by (le))",
       "legendFormat": "[95p]"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(proxy_latency_request_response_seconds_bucket{job=\"$job\", pod=~\"$pod\", tenant=\"$tenant\"}[1m])) by (le))",
       "legendFormat": "[99p]"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_threads_states_threads state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 34 },
   "repeat": "jvm_threads_states_threads",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{job=\"$job\", pod=~\"$pod\", state=\"$jvm_threads_states_threads\"}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "max"
    },
    {
     "expr": "process_memory_rss_bytes{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_pss_bytes{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "pss"
    },
    {
     "expr": "process_memory_swap_bytes{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_swappss_bytes{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "swappss"
    },
    {
     "expr": "process_memory_pss_bytes{job=\"$job\", pod=~\"$pod\"} + process_memory_swap_bytes{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "system - {{ pod }}"
    },
    {
     "expr": "process_cpu_usage{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "process - {{ pod }}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"$job\", pod=~\"$pod\"}[1h])",
     "legendFormat": "process-1h - {{ pod }}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_load_average_1m{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "system-1m"
    },
    {
     "expr": "sum(system_cpu_count{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_live_threads{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "live"
    },
    {
     "expr": "sum(jvm_threads_daemon_threads{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "daemon"
    },
    {
     "expr": "sum(jvm_threads_peak_threads{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "peak"
    },
    {
     "expr": "sum(process_threads{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(process_files_open_files{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "open"
    },
    {
     "expr": "sum(process_files_max_files{job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_heap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", pod=~\"$pod\", id=\"$jvm_memory_pool_nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_duration_seconds_count{job=\"$job\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{action}} ({{cause}}) - {{ pod }}"
    },
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"$job\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})  - {{ pod }}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_pause_duration_seconds_sum{job=\"$job\", pod=~\"$pod\"}[1m])/increase(jvm_gc_pause_duration_seconds_count{job=\"$job\", pod=~\"$pod\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}}) - {{ pod }}"
    },
    {
     "expr": "jvm_gc_pause_duration_seconds_max{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "max {{action}} ({{cause}}) - {{ pod }}"
    },
    {
     "expr": "increase(jvm_gc_pause_seconds_sum{job=\"$job\", pod=~\"$pod\"}[1m])/increase(jvm_gc_pause_seconds_count{job=\"$job\", pod=~\"$pod\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}}) - {{ pod }}"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "max {{action}} ({{cause}}) - {{ pod }}"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=\"$job\", pod=~\"$pod\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{job=\"$job\", pod=~\"$pod\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class load/unload rate (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{job=\"$job\", pod=~\"$pod\"}[5m])",
     "legendFormat": "class load rate"
    },
    {
     "expr": "delta(jvm_classes_unloaded_total{job=\"$job\", pod=~\"$pod\"}[5m])",
     "legendFormat": "class unload rate"
    },
    {
     "expr": "jvm_classes_loaded_total{job=\"$job\", pod=~\"$pod\"}-jvm_classes_unloaded_total{job=\"$job\", pod=~\"$pod\"}",
     "legendFormat": "class unload rate"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{job=\"$job\", pod=~\"$pod\", id=\"direct\"}",
     "legendFormat": "used - {{ pod }}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{job=\"$job\", pod=~\"$pod\", id=\"direct\"}",
     "legendFormat": "capacity - {{ pod }}"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{job=\"$job\", pod=~\"$pod\", id=\"direct\"}",
     "legendFormat": "count - {{ pod }}"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{job=\"$job\", pod=~\"$pod\", id=\"mapped\"}",
     "legendFormat": "used - {{ pod }}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{job=\"$job\", pod=~\"$pod\", id=\"mapped\"}",
     "legendFormat": "capacity - {{ pod }}"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{job=\"$job\", pod=~\"$pod\", id=\"mapped\"}",
     "legendFormat": "count - {{ pod }}"
    }
   ]
  }
 ]
}