apiVersion: v2
appVersion: "3.19.1"
description: Conduktor Gateway chart
icon: https://cdn.conduktor.io/brand/symbol_lime.svg
home: https://www.conduktor.io
name: conduktor-gateway
version: 3.20.1
dependencies:
  - name: common
    # force version to avoid breaking changes due to remove support for older k8s versions in common chart v2.31.0 and above
    version: 2.30.2
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: streaming-messaging
  artifacthub.io/images: |
    - name: conduktor-gateway
      image: conduktor/conduktor-gateway:3.19.0
      platforms:
        - linux/amd64
        - linux/arm64
  artifacthub.io/links: |
    - name: Changelog
      url: https://docs.conduktor.io/guide/release-notes#gateway-3--0
    - name: Documentation
      url: https://docs.conduktor.io
    - name: support
      url: https://www.conduktor.io/contact/support
  artifacthub.io/screenshots: |
    - title: Deployment architecture
      url: https://docs.conduktor.io/images/deployment-overview.png
