nameOverride: gateway-test-02

gateway:
  admin:
    port: 8888

  env:
    KAFKA_BOOTSTRAP_SERVERS: kafka.default.svc.cluster.local:9092


ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: gateway.private
  tls: true
  selfSigned: true

tests:
  enabled: true
