nameOverride: gateway-test-02

commonLabels:
  conduktor.io/team: gateway
  conduktor.io/app-env: free
  conduktor.io/env: staging

gateway:
  admin:
    port: 8888

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: gateway.private
  tls: true
  selfSigned: true

kafka:
  enabled: true
  startupProbe:
    enabled: true
    failureThreshold: 30
