nameOverride: gateway-test-06

gateway:
  replicas: 1
  securityMode: "GATEWAY_MANAGED"
  aclEnabled: "false"
  kafka:
    brokerIds:
      - "0-2"
  listeners:
    internal:
      securityProtocol: SSL
      routing: sni
      ports:
        - "9092"
  env:
    KAFKA_BOOTSTRAP_SERVERS: kafka.ct-gateway-deps.svc.cluster.local:9092
    GATEWAY_CLUSTER_ID: "gw-06"
    GATEWAY_SSL_KEY_STORE_PASSWORD: "conduktor"
    GATEWAY_SSL_KEY_PASSWORD: "conduktor"
  extraSecretEnvVars:
    - name: GATEWAY_LICENSE_KEY
      valueFrom:
        secretKeyRef:
          name: gateway-license
          key: GATEWAY_LICENSE_KEY

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  volumes:
    - name: tmp
      emptyDir: {}
  volumeMounts:
    - name: tmp
      mountPath: /tmp

podSecurityContext:
  runAsNonRoot: true

tls:
  enable: true
  secretRef: gateway-tls-keystore
  keystoreKey: keystore.jks
  keystoreFile: keystore.jks
