---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: prometheus-stack
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: admin
      admin_password: admin
  deployment:
    replicas: 1
  baseImage: grafana/grafana:10.2.2
  dashboardLabelSelector:
    - matchExpressions:
      - key: "grafana_dashboard"
        operator: In
        values: [ "1" ]
  dataStorage:
    accessModes:
      - ReadWriteOnce
    size: 1Gi
