
{{- if or .Values.console.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provisioner.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: conduktor-provisioning
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
   console-resources.yaml: |-
     # TODO
   gateway-resources.yaml: |-
     # TODO