apiVersion: v2
name: provisioner
type: application
version: 0.1.0
appVersion: "v0.5.1"
description: Helm chart to run Conduktor CLI provisioning on Conduktor Plaform
icon: https://www.conduktor.io/svgs/logo/symbol.svg
home: https://www.conduktor.io
maintainers:
  - name: Conduktor
    email: support@conduktor.io
    url: https://docs.conduktor.io/platform
sources:
  - https://github.com/conduktor/conduktor-public-charts/tree/main/charts/provisioner
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x