name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5.3.0
        with:
          gpg_private_key: ${{ secrets.CONDUKTOR_BOT_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Configure Git
        run: |
          git config user.name "${{ steps.gpg.outputs.name }}"
          git config user.email "${{ steps.gpg.outputs.email }}"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.1'

      - name: Add bitnami repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami


      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"